CREATE DATABASE IF NOT EXISTS unipulse_db;
USE unipulse_db;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  fullName VARCHAR(100) NOT NULL,
  role ENUM('student', 'organizer') NOT NULL DEFAULT 'student',
  avatar VARCHAR(255) DEFAULT NULL,
  bio TEXT DEFAULT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS events (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  description TEXT NOT NULL,
  date DATETIME NOT NULL,
  location VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL,
  maxParticipants INT NOT NULL DEFAULT 100,
  image VARCHAR(255) DEFAULT NULL,
  status ENUM('draft', 'pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending',
  organizerId INT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (organizerId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS registrations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  eventId INT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (eventId) REFERENCES events(id) ON DELETE CASCADE,
  UNIQUE KEY unique_registration (userId, eventId)
);

CREATE TABLE IF NOT EXISTS friends (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  friendId INT NOT NULL,
  status ENUM('pending', 'accepted') DEFAULT 'pending',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (friendId) REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE KEY unique_friendship (userId, friendId)
);

CREATE TABLE IF NOT EXISTS achievements (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT DEFAULT NULL,
  icon VARCHAR(255) DEFAULT NULL,
  criteria VARCHAR(255) DEFAULT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_achievements (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  achievementId INT NOT NULL,
  earnedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (achievementId) REFERENCES achievements(id) ON DELETE CASCADE,
  UNIQUE KEY unique_user_achievement (userId, achievementId)
);

CREATE TABLE IF NOT EXISTS activity_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  action VARCHAR(100) NOT NULL,
  details TEXT DEFAULT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reports (
  id INT AUTO_INCREMENT PRIMARY KEY,
  reporterId INT NOT NULL,
  targetType ENUM('user', 'event') NOT NULL,
  targetId INT NOT NULL,
  reason VARCHAR(255) NOT NULL,
  description TEXT DEFAULT NULL,
  status ENUM('pending', 'resolved') NOT NULL DEFAULT 'pending',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (reporterId) REFERENCES users(id) ON DELETE CASCADE
);

-- CREATE INDEX idx_users_role ON users(role);
-- CREATE INDEX idx_events_status ON events(status);
-- CREATE INDEX idx_events_date ON events(date);
-- CREATE INDEX idx_events_organizer ON events(organizerId);
-- CREATE INDEX idx_registrations_user ON registrations(userId);
-- CREATE INDEX idx_registrations_event ON registrations(eventId);
-- CREATE INDEX idx_activity_logs_user ON activity_logs(userId);
-- CREATE INDEX idx_reports_status ON reports(status);

USE unipulse_db;

-- Users (40 rows)
INSERT INTO users (id, username, email, password, fullName, role, avatar, bio) VALUES
(1, 'sokha_chan1', 'sokha.chan1@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER01abcdefghijklmnopqrstuv', 'Sokha Chan', 'student', NULL, NULL),
(2, 'dara_pich2', 'dara.pich2@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER02abcdefghijklmnopqrstuv', 'Dara Pich', 'student', NULL, NULL),
(3, 'sophea_heng3', 'sophea.heng3@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER03abcdefghijklmnopqrstuv', 'Sophea Heng', 'student', '/avatars/user3.png', NULL),
(4, 'vannak_sok4', 'vannak.sok4@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER04abcdefghijklmnopqrstuv', 'Vannak Sok', 'student', NULL, NULL),
(5, 'chenda_ly5', 'chenda.ly5@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER05abcdefghijklmnopqrstuv', 'Chenda Ly', 'organizer', NULL, NULL),
(6, 'pisey_meas6', 'pisey.meas6@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER06abcdefghijklmnopqrstuv', 'Pisey Meas', 'student', '/avatars/user6.png', 'Year 2 IDT student at CADT, passionate about tech events.'),
(7, 'bopha_sar7', 'bopha.sar7@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER07abcdefghijklmnopqrstuv', 'Bopha Sar', 'student', NULL, NULL),
(8, 'rithy_kong8', 'rithy.kong8@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER08abcdefghijklmnopqrstuv', 'Rithy Kong', 'student', NULL, NULL),
(9, 'sreypov_touch9', 'sreypov.touch9@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER09abcdefghijklmnopqrstuv', 'Sreypov Touch', 'student', '/avatars/user9.png', NULL),
(10, 'kosal_im10', 'kosal.im10@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER10abcdefghijklmnopqrstuv', 'Kosal Im', 'organizer', NULL, NULL),
(11, 'channary_vong11', 'channary.vong11@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER11abcdefghijklmnopqrstuv', 'Channary Vong', 'student', NULL, NULL),
(12, 'pheakdey_ros12', 'pheakdey.ros12@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER12abcdefghijklmnopqrstuv', 'Pheakdey Ros', 'student', '/avatars/user12.png', 'Year 2 IDT student at CADT, passionate about tech events.'),
(13, 'sothea_nuth13', 'sothea.nuth13@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER13abcdefghijklmnopqrstuv', 'Sothea Nuth', 'student', NULL, NULL),
(14, 'davy_khun14', 'davy.khun14@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER14abcdefghijklmnopqrstuv', 'Davy Khun', 'student', NULL, NULL),
(15, 'maline_chea15', 'maline.chea15@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER15abcdefghijklmnopqrstuv', 'Maline Chea', 'organizer', '/avatars/user15.png', NULL),
(16, 'vibol_hor16', 'vibol.hor16@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER16abcdefghijklmnopqrstuv', 'Vibol Hor', 'student', NULL, NULL),
(17, 'kanha_sam17', 'kanha.sam17@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER17abcdefghijklmnopqrstuv', 'Kanha Sam', 'student', NULL, NULL),
(18, 'veasna_phon18', 'veasna.phon18@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER18abcdefghijklmnopqrstuv', 'Veasna Phon', 'student', '/avatars/user18.png', 'Year 2 IDT student at CADT, passionate about tech events.'),
(19, 'sreyleak_ouk19', 'sreyleak.ouk19@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER19abcdefghijklmnopqrstuv', 'Sreyleak Ouk', 'student', NULL, NULL),
(20, 'borey_tep20', 'borey.tep20@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER20abcdefghijklmnopqrstuv', 'Borey Tep', 'organizer', NULL, NULL),
(21, 'sambath_yim21', 'sambath.yim21@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER21abcdefghijklmnopqrstuv', 'Sambath Yim', 'student', '/avatars/user21.png', NULL),
(22, 'chanthou_lim22', 'chanthou.lim22@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER22abcdefghijklmnopqrstuv', 'Chanthou Lim', 'student', NULL, NULL),
(23, 'pisach_khim23', 'pisach.khim23@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER23abcdefghijklmnopqrstuv', 'Pisach Khim', 'student', NULL, NULL),
(24, 'theary_chhun24', 'theary.chhun24@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER24abcdefghijklmnopqrstuv', 'Theary Chhun', 'student', '/avatars/user24.png', 'Year 2 IDT student at CADT, passionate about tech events.'),
(25, 'sovannak_mao25', 'sovannak.mao25@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER25abcdefghijklmnopqrstuv', 'Sovannak Mao', 'organizer', NULL, NULL),
(26, 'lina_eng26', 'lina.eng26@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER26abcdefghijklmnopqrstuv', 'Lina Eng', 'student', NULL, NULL),
(27, 'vuthy_dorn27', 'vuthy.dorn27@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER27abcdefghijklmnopqrstuv', 'Vuthy Dorn', 'student', '/avatars/user27.png', NULL),
(28, 'sreypich_hak28', 'sreypich.hak28@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER28abcdefghijklmnopqrstuv', 'Sreypich Hak', 'student', NULL, NULL),
(29, 'phanith_loeung29', 'phanith.loeung29@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER29abcdefghijklmnopqrstuv', 'Phanith Loeung', 'student', NULL, NULL),
(30, 'reaksmey_choun30', 'reaksmey.choun30@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER30abcdefghijklmnopqrstuv', 'Reaksmey Choun', 'organizer', '/avatars/user30.png', 'Year 2 IDT student at CADT, passionate about tech events.'),
(31, 'sambo_heng31', 'sambo.heng31@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER31abcdefghijklmnopqrstuv', 'Sambo Heng', 'student', NULL, NULL),
(32, 'sina_pen32', 'sina.pen32@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER32abcdefghijklmnopqrstuv', 'Sina Pen', 'student', NULL, NULL),
(33, 'kunthea_sok33', 'kunthea.sok33@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER33abcdefghijklmnopqrstuv', 'Kunthea Sok', 'student', '/avatars/user33.png', NULL),
(34, 'narith_vong34', 'narith.vong34@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER34abcdefghijklmnopqrstuv', 'Narith Vong', 'student', NULL, NULL),
(35, 'chetra_lay35', 'chetra.lay35@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER35abcdefghijklmnopqrstuv', 'Chetra Lay', 'organizer', NULL, NULL),
(36, 'phalla_mom36', 'phalla.mom36@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER36abcdefghijklmnopqrstuv', 'Phalla Mom', 'student', '/avatars/user36.png', 'Year 2 IDT student at CADT, passionate about tech events.'),
(37, 'sothy_keo37', 'sothy.keo37@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER37abcdefghijklmnopqrstuv', 'Sothy Keo', 'student', NULL, NULL),
(38, 'dany_roeun38', 'dany.roeun38@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER38abcdefghijklmnopqrstuv', 'Dany Roeun', 'student', NULL, NULL),
(39, 'sreyneang_kann39', 'sreyneang.kann39@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER39abcdefghijklmnopqrstuv', 'Sreyneang Kann', 'student', '/avatars/user39.png', NULL),
(40, 'vichet_tha40', 'vichet.tha40@cadt.edu.kh', '$2b$10$EXAMPLEHASHPLACEHOLDER40abcdefghijklmnopqrstuv', 'Vichet Tha', 'organizer', NULL, NULL);

-- Events (40 rows)
INSERT INTO events (id, title, description, date, location, category, maxParticipants, image, status, organizerId) VALUES
(1, 'Freshman Welcome Day', 'Join us for Freshman Welcome Day, an event organized by CADT students to bring the community together and build new skills.', '2026-01-19 13:00:00', 'CADT Auditorium', 'Sports', 50, NULL, 'approved', 5),
(2, 'Hackathon: Code for Cambodia', 'Join us for Hackathon: Code for Cambodia, an event organized by CADT students to bring the community together and build new skills.', '2026-01-28 15:30:00', 'Olympic Stadium, Phnom Penh', 'Cultural', 70, NULL, 'approved', 40),
(3, 'Khmer New Year Cultural Fair', 'Join us for Khmer New Year Cultural Fair, an event organized by CADT students to bring the community together and build new skills.', '2026-02-06 18:00:00', 'Diamond Island Convention Center', 'Workshop', 90, NULL, 'approved', 10),
(4, 'Inter-University Football Cup', 'Join us for Inter-University Football Cup, an event organized by CADT students to bring the community together and build new skills.', '2026-02-15 09:00:00', 'Riverside Park, Phnom Penh', 'Career', 110, '/events/event4.jpg', 'approved', 15),
(5, 'AI & Machine Learning Workshop', 'Join us for AI & Machine Learning Workshop, an event organized by CADT students to bring the community together and build new skills.', '2026-02-24 13:00:00', 'Wat Phnom Park', 'Social', 130, NULL, 'pending', 20),
(6, 'Career Fair: Tech Industry Day', 'Join us for Career Fair: Tech Industry Day, an event organized by CADT students to bring the community together and build new skills.', '2026-03-05 15:30:00', 'AEON Mall Sen Sok', 'Tech', 150, NULL, 'approved', 25),
(7, 'Photography Club Exhibition', 'Join us for Photography Club Exhibition, an event organized by CADT students to bring the community together and build new skills.', '2026-03-14 18:00:00', 'Institute of Technology of Cambodia Campus', 'Volunteer', 170, NULL, 'approved', 30),
(8, 'Coding Bootcamp Kickoff', 'Join us for Coding Bootcamp Kickoff, an event organized by CADT students to bring the community together and build new skills.', '2026-03-23 09:00:00', 'Royal University of Phnom Penh Campus', 'Music', 30, '/events/event8.jpg', 'approved', 35),
(9, 'Volunteer Beach Cleanup', 'Join us for Volunteer Beach Cleanup, an event organized by CADT students to bring the community together and build new skills.', '2026-04-01 13:00:00', 'Koh Pich Garden City', 'Gaming', 50, NULL, 'approved', 5),
(10, 'Mid-Autumn Lantern Festival', 'Join us for Mid-Autumn Lantern Festival, an event organized by CADT students to bring the community together and build new skills.', '2026-04-10 15:30:00', 'Chaktomuk Conference Hall', 'Academic', 70, NULL, 'pending', 40),
(11, 'Esports Tournament: Mobile Legends', 'Join us for Esports Tournament: Mobile Legends, an event organized by CADT students to bring the community together and build new skills.', '2026-04-19 18:00:00', 'CADT Library Courtyard', 'Sports', 90, NULL, 'approved', 10),
(12, 'Public Speaking Workshop', 'Join us for Public Speaking Workshop, an event organized by CADT students to bring the community together and build new skills.', '2026-04-28 09:00:00', 'CADT Rooftop', 'Cultural', 110, '/events/event12.jpg', 'approved', 15),
(13, 'Startup Pitch Night', 'Join us for Startup Pitch Night, an event organized by CADT students to bring the community together and build new skills.', '2026-05-07 13:00:00', 'Naga World Convention Hall', 'Workshop', 130, NULL, 'approved', 20),
(14, 'Robotics Showcase', 'Join us for Robotics Showcase, an event organized by CADT students to bring the community together and build new skills.', '2026-05-16 15:30:00', 'Phnom Penh Convention Center', 'Career', 150, NULL, 'approved', 25),
(15, 'Traditional Khmer Dance Performance', 'Join us for Traditional Khmer Dance Performance, an event organized by CADT students to bring the community together and build new skills.', '2026-05-25 18:00:00', 'CADT Main Hall, Phnom Penh', 'Social', 170, NULL, 'pending', 30),
(16, 'Database Design Seminar', 'Join us for Database Design Seminar, an event organized by CADT students to bring the community together and build new skills.', '2026-06-03 09:00:00', 'CADT Auditorium', 'Tech', 30, '/events/event16.jpg', 'approved', 35),
(17, 'Basketball 3v3 Tournament', 'Join us for Basketball 3v3 Tournament, an event organized by CADT students to bring the community together and build new skills.', '2026-06-12 13:00:00', 'Olympic Stadium, Phnom Penh', 'Volunteer', 50, NULL, 'approved', 5),
(18, 'Open Mic Music Night', 'Join us for Open Mic Music Night, an event organized by CADT students to bring the community together and build new skills.', '2026-06-21 15:30:00', 'Diamond Island Convention Center', 'Music', 70, NULL, 'approved', 40),
(19, 'UX/UI Design Sprint', 'Join us for UX/UI Design Sprint, an event organized by CADT students to bring the community together and build new skills.', '2026-06-30 18:00:00', 'Riverside Park, Phnom Penh', 'Gaming', 90, NULL, 'approved', 10),
(20, 'Blood Donation Drive', 'Join us for Blood Donation Drive, an event organized by CADT students to bring the community together and build new skills.', '2026-07-09 09:00:00', 'Wat Phnom Park', 'Academic', 110, '/events/event20.jpg', 'pending', 15),
(21, 'Cybersecurity Awareness Talk', 'Join us for Cybersecurity Awareness Talk, an event organized by CADT students to bring the community together and build new skills.', '2026-07-18 13:00:00', 'AEON Mall Sen Sok', 'Sports', 130, NULL, 'approved', 20),
(22, 'Badminton Friendly Match', 'Join us for Badminton Friendly Match, an event organized by CADT students to bring the community together and build new skills.', '2026-07-27 15:30:00', 'Institute of Technology of Cambodia Campus', 'Cultural', 150, NULL, 'approved', 25),
(23, 'Cambodian Cuisine Cooking Class', 'Join us for Cambodian Cuisine Cooking Class, an event organized by CADT students to bring the community together and build new skills.', '2026-08-05 18:00:00', 'Royal University of Phnom Penh Campus', 'Workshop', 170, NULL, 'approved', 30),
(24, 'CADT Job Shadowing Day', 'Join us for CADT Job Shadowing Day, an event organized by CADT students to bring the community together and build new skills.', '2026-08-14 09:00:00', 'Koh Pich Garden City', 'Career', 30, '/events/event24.jpg', 'approved', 35),
(25, 'Web Development Workshop', 'Join us for Web Development Workshop, an event organized by CADT students to bring the community together and build new skills.', '2026-08-23 13:00:00', 'Chaktomuk Conference Hall', 'Social', 50, NULL, 'pending', 5),
(26, 'Chess Club Championship', 'Join us for Chess Club Championship, an event organized by CADT students to bring the community together and build new skills.', '2026-09-01 15:30:00', 'CADT Library Courtyard', 'Tech', 70, NULL, 'approved', 40),
(27, 'Environmental Sustainability Talk', 'Join us for Environmental Sustainability Talk, an event organized by CADT students to bring the community together and build new skills.', '2026-09-10 18:00:00', 'CADT Rooftop', 'Volunteer', 90, NULL, 'approved', 10),
(28, 'Anime & Manga Club Meetup', 'Join us for Anime & Manga Club Meetup, an event organized by CADT students to bring the community together and build new skills.', '2026-09-19 09:00:00', 'Naga World Convention Hall', 'Music', 110, '/events/event28.jpg', 'approved', 15),
(29, 'Entrepreneurship Bootcamp', 'Join us for Entrepreneurship Bootcamp, an event organized by CADT students to bring the community together and build new skills.', '2026-09-28 13:00:00', 'Phnom Penh Convention Center', 'Gaming', 130, NULL, 'approved', 20),
(30, 'Volleyball Inter-Class League', 'Join us for Volleyball Inter-Class League, an event organized by CADT students to bring the community together and build new skills.', '2026-10-07 15:30:00', 'CADT Main Hall, Phnom Penh', 'Academic', 150, NULL, 'pending', 25),
(31, 'Data Science Study Jam', 'Join us for Data Science Study Jam, an event organized by CADT students to bring the community together and build new skills.', '2026-10-16 18:00:00', 'CADT Auditorium', 'Sports', 170, NULL, 'approved', 30),
(32, 'Mobile App Dev Workshop', 'Join us for Mobile App Dev Workshop, an event organized by CADT students to bring the community together and build new skills.', '2026-10-25 09:00:00', 'Olympic Stadium, Phnom Penh', 'Cultural', 30, '/events/event32.jpg', 'approved', 35),
(33, 'Community Service Day at Pagoda', 'Join us for Community Service Day at Pagoda, an event organized by CADT students to bring the community together and build new skills.', '2026-11-03 13:00:00', 'Diamond Island Convention Center', 'Workshop', 50, NULL, 'approved', 5),
(34, 'Karaoke Night', 'Join us for Karaoke Night, an event organized by CADT students to bring the community together and build new skills.', '2026-11-12 15:30:00', 'Riverside Park, Phnom Penh', 'Career', 70, NULL, 'approved', 40),
(35, 'CADT Alumni Networking Event', 'Join us for CADT Alumni Networking Event, an event organized by CADT students to bring the community together and build new skills.', '2026-11-21 18:00:00', 'Wat Phnom Park', 'Social', 90, NULL, 'pending', 10),
(36, 'Cloud Computing Workshop', 'Join us for Cloud Computing Workshop, an event organized by CADT students to bring the community together and build new skills.', '2026-11-30 09:00:00', 'AEON Mall Sen Sok', 'Tech', 110, '/events/event36.jpg', 'approved', 15),
(37, 'Board Game Night', 'Join us for Board Game Night, an event organized by CADT students to bring the community together and build new skills.', '2026-01-13 13:00:00', 'Institute of Technology of Cambodia Campus', 'Volunteer', 130, NULL, 'approved', 20),
(38, 'Swimming Gala', 'Join us for Swimming Gala, an event organized by CADT students to bring the community together and build new skills.', '2026-01-22 15:30:00', 'Royal University of Phnom Penh Campus', 'Music', 150, NULL, 'approved', 25),
(39, 'Public Health Awareness Seminar', 'Join us for Public Health Awareness Seminar, an event organized by CADT students to bring the community together and build new skills.', '2026-01-31 18:00:00', 'Koh Pich Garden City', 'Gaming', 170, NULL, 'approved', 30),
(40, 'Graduation Send-off Party', 'Join us for Graduation Send-off Party, an event organized by CADT students to bring the community together and build new skills.', '2026-02-09 09:00:00', 'Chaktomuk Conference Hall', 'Academic', 30, '/events/event40.jpg', 'pending', 35);

-- Registrations (40 rows)
INSERT INTO registrations (id, userId, eventId) VALUES
(1, 1, 3),
(2, 2, 6),
(3, 3, 9),
(4, 4, 12),
(5, 5, 15),
(6, 6, 18),
(7, 7, 21),
(8, 8, 24),
(9, 9, 27),
(10, 10, 30),
(11, 11, 33),
(12, 12, 36),
(13, 13, 39),
(14, 14, 2),
(15, 15, 5),
(16, 16, 8),
(17, 17, 11),
(18, 18, 14),
(19, 19, 17),
(20, 20, 20),
(21, 21, 23),
(22, 22, 26),
(23, 23, 29),
(24, 24, 32),
(25, 25, 35),
(26, 26, 38),
(27, 27, 1),
(28, 28, 4),
(29, 29, 7),
(30, 30, 10),
(31, 31, 13),
(32, 32, 16),
(33, 33, 19),
(34, 34, 22),
(35, 35, 25),
(36, 36, 28),
(37, 37, 31),
(38, 38, 34),
(39, 39, 37),
(40, 40, 40);

-- Friends (40 rows)
INSERT INTO friends (id, userId, friendId) VALUES
(1, 1, 6),
(2, 2, 7),
(3, 3, 8),
(4, 4, 9),
(5, 5, 10),
(6, 6, 11),
(7, 7, 12),
(8, 8, 13),
(9, 9, 14),
(10, 10, 15),
(11, 11, 16),
(12, 12, 17),
(13, 13, 18),
(14, 14, 19),
(15, 15, 20),
(16, 16, 21),
(17, 17, 22),
(18, 18, 23),
(19, 19, 24),
(20, 20, 25),
(21, 21, 26),
(22, 22, 27),
(23, 23, 28),
(24, 24, 29),
(25, 25, 30),
(26, 26, 31),
(27, 27, 32),
(28, 28, 33),
(29, 29, 34),
(30, 30, 35),
(31, 31, 36),
(32, 32, 37),
(33, 33, 38),
(34, 34, 39),
(35, 35, 40),
(36, 36, 1),
(37, 37, 2),
(38, 38, 3),
(39, 39, 4),
(40, 40, 5);

-- Achievements (40 rows)
INSERT INTO achievements (id, name, description, icon, criteria) VALUES
(1, 'First Steps', 'Register for your first event', '/icons/first_steps.png', 'register_1_event'),
(2, 'Social Butterfly', 'Add 5 friends on UniPulse', '/icons/social_butterfly.png', 'add_5_friends'),
(3, 'Event Explorer', 'Attend 5 different events', '/icons/event_explorer.png', 'attend_5_events'),
(4, 'Event Organizer', 'Create your first event', '/icons/event_organizer.png', 'create_1_event'),
(8, 'Crowd Pleaser', 'Organize an event with 100+ participants', '/icons/crowd_pleaser.png', 'event_100_participants'),
(9, 'Tech Enthusiast', 'Attend 3 Tech category events', '/icons/tech_enthusiast.png', 'attend_3_tech_events'),
(10, 'Sports Fanatic', 'Attend 3 Sports category events', '/icons/sports_fanatic.png', 'attend_3_sports_events'),
(11, 'Culture Keeper', 'Attend 3 Cultural category events', '/icons/culture_keeper.png', 'attend_3_cultural_events'),
(12, 'Volunteer Hero', 'Attend 3 Volunteer category events', '/icons/volunteer_hero.png', 'attend_3_volunteer_events'),
(13, 'Networking Pro', 'Add 10 friends on UniPulse', '/icons/networking_pro.png', 'add_10_friends'),
(14, 'Early Bird', 'Register for an event within 1 hour of posting', '/icons/early_bird.png', 'early_registration'),
(15, 'Feedback Champion', 'Submit 5 event reviews', '/icons/feedback_champion.png', 'submit_5_reviews'),
(16, 'Workshop Wizard', 'Attend 5 Workshop category events', '/icons/workshop_wizard.png', 'attend_5_workshops'),
(17, 'Music Lover', 'Attend 3 Music category events', '/icons/music_lover.png', 'attend_3_music_events'),
(18, 'Gamer Tag', 'Attend 3 Gaming category events', '/icons/gamer_tag.png', 'attend_3_gaming_events'),
(19, 'Career Builder', 'Attend 3 Career category events', '/icons/career_builder.png', 'attend_3_career_events'),
(20, 'Community Pillar', 'Organize 5 events', '/icons/community_pillar.png', 'create_5_events'),
(21, 'Loyal Member', 'Active on UniPulse for 6 months', '/icons/loyal_member.png', 'active_6_months'),
(22, 'Founding Member', 'Joined UniPulse in its first month', '/icons/founding_member.png', 'early_adopter'),
(23, 'Profile Complete', 'Fill out your full profile with bio and avatar', '/icons/profile_complete.png', 'complete_profile'),
(24, 'Report Responsible', 'Submit a verified report', '/icons/report_responsible.png', 'submit_verified_report'),
(25, 'Event Veteran', 'Attend 20 events total', '/icons/event_veteran.png', 'attend_20_events'),
(27, 'Friendly Face', 'Add 20 friends on UniPulse', '/icons/friendly_face.png', 'add_20_friends'),
(28, 'Top Organizer', 'Organize 10 approved events', '/icons/top_organizer.png', 'create_10_approved_events'),
(29, 'Cultural Ambassador', 'Attend 10 Cultural category events', '/icons/cultural_ambassador.png', 'attend_10_cultural_events'),
(30, 'Tech Guru', 'Attend 10 Tech category events', '/icons/tech_guru.png', 'attend_10_tech_events'),
(31, 'Helping Hand', 'Volunteer at 5 events', '/icons/helping_hand.png', 'volunteer_5_events'),
(32, 'Sportsman Spirit', 'Attend 10 Sports category events', '/icons/sportsman_spirit.png', 'attend_10_sports_events'),
(33, 'Night Owl', 'Attend an event starting after 18:00', '/icons/night_owl.png', 'attend_evening_event'),
(34, 'Trendsetter', 'Be among first 10 registrants of an event', '/icons/trendsetter.png', 'early_top10_registrant'),
(35, 'Perfect Attendance', 'Attend every event you registered for in a month', '/icons/perfect_attendance.png', 'perfect_attendance_month'),
(36, 'Mentor', 'Help onboard 3 new students', '/icons/mentor.png', 'mentor_3_students'),
(37, 'Big Spender Free', 'Register for 15 events in a semester', '/icons/big_spender.png', 'register_15_events_semester'),
(38, 'Graduation Ready', 'Attend the graduation send-off event', '/icons/graduation_ready.png', 'attend_graduation_event'),
(40, 'CADT Champion', 'Earn 10 different achievements', '/icons/cadt_champion.png', 'earn_10_achievements');

-- User Achievements (40 rows)
INSERT INTO user_achievements (id, userId, achievementId, earnedAt) VALUES
(1, 1, 7, '2026-01-11 10:00:00'),
(2, 2, 14, '2026-01-12 10:00:00'),
(3, 3, 21, '2026-01-13 10:00:00'),
(4, 4, 28, '2026-01-14 10:00:00'),
(5, 5, 35, '2026-01-15 10:00:00'),
(6, 6, 2, '2026-01-16 10:00:00'),
(7, 7, 9, '2026-01-17 10:00:00'),
(8, 8, 16, '2026-01-18 10:00:00'),
(9, 9, 23, '2026-01-19 10:00:00'),
(10, 10, 30, '2026-01-20 10:00:00'),
(11, 11, 37, '2026-01-21 10:00:00'),
(12, 12, 4, '2026-01-22 10:00:00'),
(13, 13, 11, '2026-01-23 10:00:00'),
(14, 14, 18, '2026-01-24 10:00:00'),
(15, 15, 25, '2026-01-25 10:00:00'),
(16, 16, 32, '2026-01-26 10:00:00'),
(17, 17, 39, '2026-01-27 10:00:00'),
(18, 18, 6, '2026-01-28 10:00:00'),
(19, 19, 13, '2026-01-29 10:00:00'),
(20, 20, 20, '2026-01-30 10:00:00'),
(21, 21, 27, '2026-01-31 10:00:00'),
(22, 22, 34, '2026-02-01 10:00:00'),
(23, 23, 1, '2026-02-02 10:00:00'),
(24, 24, 8, '2026-02-03 10:00:00'),
(25, 25, 15, '2026-02-04 10:00:00'),
(26, 26, 22, '2026-02-05 10:00:00'),
(27, 27, 29, '2026-02-06 10:00:00'),
(28, 28, 36, '2026-02-07 10:00:00'),
(29, 29, 3, '2026-02-08 10:00:00'),
(30, 30, 10, '2026-02-09 10:00:00'),
(31, 31, 17, '2026-02-10 10:00:00'),
(32, 32, 24, '2026-02-11 10:00:00'),
(33, 33, 31, '2026-02-12 10:00:00'),
(34, 34, 38, '2026-02-13 10:00:00'),
(35, 35, 5, '2026-02-14 10:00:00'),
(36, 36, 12, '2026-02-15 10:00:00'),
(37, 37, 19, '2026-02-16 10:00:00'),
(38, 38, 26, '2026-02-17 10:00:00'),
(39, 39, 33, '2026-02-18 10:00:00'),
(40, 40, 40, '2026-02-19 10:00:00');

-- Activity Logs (40 rows)
INSERT INTO activity_logs (id, userId, action, details) VALUES
(1, 2, 'event_register', 'User performed event register action on the UniPulse platform.'),
(2, 4, 'event_unregister', 'User performed event unregister action on the UniPulse platform.'),
(3, 6, 'achievement_earned', 'User performed achievement earned action on the UniPulse platform.'),
(4, 8, 'event_view', 'User performed event view action on the UniPulse platform.'),
(5, 10, 'event_create', 'User performed event create action on the UniPulse platform.'),
(6, 12, 'profile_update', 'User performed profile update action on the UniPulse platform.'),
(7, 14, 'friend_add', 'User performed friend add action on the UniPulse platform.'),
(8, 16, 'comment_post', 'User performed comment post action on the UniPulse platform.'),
(9, 18, 'event_view', 'User performed event view action on the UniPulse platform.'),
(10, 20, 'login', 'User performed login action on the UniPulse platform.'),
(11, 22, 'event_register', 'User performed event register action on the UniPulse platform.'),
(12, 24, 'event_unregister', 'User performed event unregister action on the UniPulse platform.'),
(13, 26, 'achievement_earned', 'User performed achievement earned action on the UniPulse platform.'),
(14, 28, 'event_view', 'User performed event view action on the UniPulse platform.'),
(15, 30, 'event_create', 'User performed event create action on the UniPulse platform.'),
(16, 32, 'profile_update', 'User performed profile update action on the UniPulse platform.'),
(17, 34, 'friend_add', 'User performed friend add action on the UniPulse platform.'),
(18, 36, 'comment_post', 'User performed comment post action on the UniPulse platform.'),
(19, 38, 'event_view', 'User performed event view action on the UniPulse platform.'),
(20, 40, 'login', 'User performed login action on the UniPulse platform.'),
(21, 2, 'event_register', 'User performed event register action on the UniPulse platform.'),
(22, 4, 'event_unregister', 'User performed event unregister action on the UniPulse platform.'),
(23, 6, 'achievement_earned', 'User performed achievement earned action on the UniPulse platform.'),
(24, 8, 'event_view', 'User performed event view action on the UniPulse platform.'),
(25, 10, 'event_create', 'User performed event create action on the UniPulse platform.'),
(26, 12, 'profile_update', 'User performed profile update action on the UniPulse platform.'),
(27, 14, 'friend_add', 'User performed friend add action on the UniPulse platform.'),
(28, 16, 'comment_post', 'User performed comment post action on the UniPulse platform.'),
(29, 18, 'event_view', 'User performed event view action on the UniPulse platform.'),
(30, 20, 'login', 'User performed login action on the UniPulse platform.'),
(31, 22, 'event_register', 'User performed event register action on the UniPulse platform.'),
(32, 24, 'event_unregister', 'User performed event unregister action on the UniPulse platform.'),
(33, 26, 'achievement_earned', 'User performed achievement earned action on the UniPulse platform.'),
(34, 28, 'event_view', 'User performed event view action on the UniPulse platform.'),
(35, 30, 'event_create', 'User performed event create action on the UniPulse platform.'),
(36, 32, 'profile_update', 'User performed profile update action on the UniPulse platform.'),
(37, 34, 'friend_add', 'User performed friend add action on the UniPulse platform.'),
(38, 36, 'comment_post', 'User performed comment post action on the UniPulse platform.'),
(39, 38, 'event_view', 'User performed event view action on the UniPulse platform.'),
(40, 40, 'login', 'User performed login action on the UniPulse platform.');

-- Reports (40 rows)
INSERT INTO reports (id, reporterId, targetType, targetId, reason, description, status) VALUES
(1, 5, 'event', 3, 'Spam', 'Reported event for: spam.', 'pending'),
(2, 10, 'user', 5, 'Harassment', 'Reported user for: harassment.', 'pending'),
(3, 15, 'event', 7, 'Fake event', 'Reported event for: fake event.', 'resolved'),
(4, 20, 'user', 9, 'Duplicate account', 'Reported user for: duplicate account.', 'pending'),
(5, 25, 'event', 11, 'Misleading information', 'Reported event for: misleading information.', 'pending'),
(6, 30, 'user', 13, 'Offensive language', 'Reported user for: offensive language.', 'resolved'),
(7, 35, 'event', 15, 'Scam attempt', 'Reported event for: scam attempt.', 'pending'),
(8, 40, 'user', 17, 'Inappropriate content', 'Reported user for: inappropriate content.', 'pending'),
(9, 5, 'event', 19, 'Spam', 'Reported event for: spam.', 'resolved'),
(10, 10, 'user', 21, 'Harassment', 'Reported user for: harassment.', 'pending'),
(11, 15, 'event', 23, 'Fake event', 'Reported event for: fake event.', 'pending'),
(12, 20, 'user', 25, 'Duplicate account', 'Reported user for: duplicate account.', 'resolved'),
(13, 25, 'event', 27, 'Misleading information', 'Reported event for: misleading information.', 'pending'),
(14, 30, 'user', 29, 'Offensive language', 'Reported user for: offensive language.', 'pending'),
(15, 35, 'event', 31, 'Scam attempt', 'Reported event for: scam attempt.', 'resolved'),
(16, 40, 'user', 33, 'Inappropriate content', 'Reported user for: inappropriate content.', 'pending'),
(17, 5, 'event', 35, 'Spam', 'Reported event for: spam.', 'pending'),
(18, 10, 'user', 37, 'Harassment', 'Reported user for: harassment.', 'resolved'),
(19, 15, 'event', 39, 'Fake event', 'Reported event for: fake event.', 'pending'),
(20, 20, 'user', 1, 'Duplicate account', 'Reported user for: duplicate account.', 'pending'),
(21, 25, 'event', 3, 'Misleading information', 'Reported event for: misleading information.', 'resolved'),
(22, 30, 'user', 5, 'Offensive language', 'Reported user for: offensive language.', 'pending'),
(23, 35, 'event', 7, 'Scam attempt', 'Reported event for: scam attempt.', 'pending'),
(24, 40, 'user', 9, 'Inappropriate content', 'Reported user for: inappropriate content.', 'resolved'),
(25, 5, 'event', 11, 'Spam', 'Reported event for: spam.', 'pending'),
(26, 10, 'user', 13, 'Harassment', 'Reported user for: harassment.', 'pending'),
(27, 15, 'event', 15, 'Fake event', 'Reported event for: fake event.', 'resolved'),
(28, 20, 'user', 17, 'Duplicate account', 'Reported user for: duplicate account.', 'pending'),
(29, 25, 'event', 19, 'Misleading information', 'Reported event for: misleading information.', 'pending'),
(30, 30, 'user', 21, 'Offensive language', 'Reported user for: offensive language.', 'resolved'),
(31, 35, 'event', 23, 'Scam attempt', 'Reported event for: scam attempt.', 'pending'),
(32, 40, 'user', 25, 'Inappropriate content', 'Reported user for: inappropriate content.', 'pending'),
(33, 5, 'event', 27, 'Spam', 'Reported event for: spam.', 'resolved'),
(34, 10, 'user', 29, 'Harassment', 'Reported user for: harassment.', 'pending'),
(35, 15, 'event', 31, 'Fake event', 'Reported event for: fake event.', 'pending'),
(36, 20, 'user', 33, 'Duplicate account', 'Reported user for: duplicate account.', 'resolved'),
(37, 25, 'event', 35, 'Misleading information', 'Reported event for: misleading information.', 'pending'),
(38, 30, 'user', 37, 'Offensive language', 'Reported user for: offensive language.', 'pending'),
(39, 35, 'event', 39, 'Scam attempt', 'Reported event for: scam attempt.', 'resolved'),
(40, 40, 'user', 1, 'Inappropriate content', 'Reported user for: inappropriate content.', 'pending');