ALTER TABLE users ADD COLUMN IF NOT EXISTS otp VARCHAR(6) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS otpExpiresAt DATETIME DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS isVerified BOOLEAN DEFAULT FALSE;
UPDATE users SET isVerified = TRUE WHERE isVerified IS NULL OR isVerified = FALSE;
